# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\program\SecretChat - 公共发布版\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(337, 409)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_fresh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fresh.sizePolicy().hasHeightForWidth())
        self.pushButton_fresh.setSizePolicy(sizePolicy)
        self.pushButton_fresh.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_fresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_fresh.setObjectName("pushButton_fresh")
        self.horizontalLayout_2.addWidget(self.pushButton_fresh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_create_conversation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create_conversation.setObjectName("pushButton_create_conversation")
        self.horizontalLayout.addWidget(self.pushButton_create_conversation)
        self.pushButton_delete_conversation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_conversation.setObjectName("pushButton_delete_conversation")
        self.horizontalLayout.addWidget(self.pushButton_delete_conversation)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_about_author = QtWidgets.QAction(MainWindow)
        self.action_about_author.setObjectName("action_about_author")
        self.action_about_program = QtWidgets.QAction(MainWindow)
        self.action_about_program.setObjectName("action_about_program")
        self.menu.addAction(self.action_about_program)
        self.menu.addAction(self.action_about_author)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "对话管理"))
        self.pushButton_fresh.setText(_translate("MainWindow", "刷新"))
        self.pushButton_create_conversation.setText(_translate("MainWindow", "添加对话"))
        self.pushButton_delete_conversation.setText(_translate("MainWindow", "删除对话"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.action_about_author.setText(_translate("MainWindow", "关于作者"))
        self.action_about_program.setText(_translate("MainWindow", "关于本程序"))
